import { createContext, useContext } from 'react';

interface DemoContextValue {
  isDemoMode: boolean;
}

export const DemoContext = createContext<DemoContextValue>({ isDemoMode: false });

export function useDemoMode(): boolean {
  return useContext(DemoContext).isDemoMode;
}

// ─── Demo Data Constants ─────────────────────────────────────────────
// Realistic, impressive demo data used across components when in demo mode

export const DEMO_DASHBOARD_STATS = {
  totalLeads: 1847,
  totalCampaigns: 12,
  emailsSent: 4832,
  emailsOpened: 2174,
  emailsClicked: 687,
  openRate: 45.0,
  clickRate: 14.2,
  deliveryRate: 97.8,
  emailsDelivered: 4726,
  emailsReplied: 312,
  linkClicks: 421,
  leadsHistory: [820, 960, 1100, 1280, 1420, 1580, 1720, 1847],
  campaignsHistory: [3, 4, 5, 6, 7, 8, 10, 12],
  emailsHistory: [1200, 1800, 2400, 3000, 3500, 4000, 4400, 4832],
  opensHistory: [540, 810, 1080, 1350, 1575, 1800, 1980, 2174],
  clicksHistory: [170, 255, 340, 425, 497, 568, 624, 687],
  deliveryHistory: [96.5, 97.0, 97.2, 97.5, 97.6, 97.7, 97.8, 97.8],
};

export const DEMO_REVENUE_SNAP = {
  mrr: 34200,
  pipelineValue: 489000,
  activeDeals: 41,
  wonDeals: 24,
  closeRate: 58.5,
};

// Revenue page demo data
export const DEMO_REVENUE_METRICS = {
  brand: 'default',
  total_revenue: 284750,
  monthly_revenue: 47200,
  weekly_revenue: 11800,
  daily_revenue: 1690,
  mrr: 38400,
  arr: 460800,
  total_customers: 156,
  active_subscriptions: 89,
  churn_rate: 3.2,
  avg_deal_size: 1825,
  conversion_rate: 12.4,
  revenue_per_lead: 22.60,
  updated_at: new Date().toISOString(),
};

export const DEMO_ANALYTICS_TRACKING = {
  websites: [
    {
      id: 'demo-site-1',
      domain: 'contndr.com',
      name: 'Contndr Marketing Site',
      isTracking: true,
      totalVisits: 12847,
      uniqueVisitors: 8432,
      pageViews: 28934,
      avgSessionDuration: 245,
      bounceRate: 42.3,
      topPages: [
        { path: '/', views: 8234, uniqueVisitors: 5621 },
        { path: '/pricing', views: 4521, uniqueVisitors: 3012 },
        { path: '/features', views: 3842, uniqueVisitors: 2534 },
        { path: '/demo', views: 2891, uniqueVisitors: 2104 },
      ],
      recentActivity: [
        { timestamp: new Date(Date.now() - 5 * 60000).toISOString(), page: '/pricing', visitor: 'visitor-001', location: 'San Francisco, CA' },
        { timestamp: new Date(Date.now() - 12 * 60000).toISOString(), page: '/features', visitor: 'visitor-002', location: 'New York, NY' },
        { timestamp: new Date(Date.now() - 18 * 60000).toISOString(), page: '/', visitor: 'visitor-003', location: 'Austin, TX' },
      ],
    },
    {
      id: 'demo-site-2',
      domain: 'app.contndr.com',
      name: 'Contndr App',
      isTracking: true,
      totalVisits: 8421,
      uniqueVisitors: 4234,
      pageViews: 18932,
      avgSessionDuration: 428,
      bounceRate: 18.7,
      topPages: [
        { path: '/dashboard', views: 5234, uniqueVisitors: 2891 },
        { path: '/campaigns', views: 3842, uniqueVisitors: 1923 },
        { path: '/crm', views: 2934, uniqueVisitors: 1542 },
      ],
      recentActivity: [
        { timestamp: new Date(Date.now() - 3 * 60000).toISOString(), page: '/dashboard', visitor: 'user-042', location: 'Seattle, WA' },
        { timestamp: new Date(Date.now() - 8 * 60000).toISOString(), page: '/campaigns', visitor: 'user-018', location: 'Boston, MA' },
      ],
    },
  ],
  totalTrackedSites: 2,
  activeVisitors: 14,
  last24hVisits: 1847,
  conversionEvents: [
    { event: 'signup_completed', count: 42, lastTriggered: new Date(Date.now() - 45 * 60000).toISOString() },
    { event: 'demo_requested', count: 18, lastTriggered: new Date(Date.now() - 120 * 60000).toISOString() },
    { event: 'trial_started', count: 31, lastTriggered: new Date(Date.now() - 90 * 60000).toISOString() },
  ],
};

export const DEMO_CAMPAIGNS = [
  {
    id: 'demo-camp-1',
    name: 'Q1 Enterprise Outreach',
    product: 'Contndr Growth',
    brand: 'contndr',
    tone: 'professional',
    status: 'active',
    from_email: 'alex@contndr.com',
    created_at: '2026-02-15T10:00:00Z',
    is_own: true,
    lead_count: 340,
    sent_count: 312,
    open_count: 156,
    click_count: 48,
    reply_count: 31,
    bounce_count: 4,
  },
  {
    id: 'demo-camp-2',
    name: 'SaaS Decision Makers',
    product: 'Contndr Pro',
    brand: 'contndr',
    tone: 'casual',
    status: 'active',
    from_email: 'alex@contndr.com',
    created_at: '2026-02-20T14:30:00Z',
    is_own: true,
    lead_count: 520,
    sent_count: 480,
    open_count: 264,
    click_count: 82,
    reply_count: 54,
    bounce_count: 6,
  },
  {
    id: 'demo-camp-3',
    name: 'Agency Partnership Intro',
    product: 'Contndr Agency',
    brand: 'contndr',
    tone: 'friendly',
    status: 'completed',
    from_email: 'partnerships@contndr.com',
    created_at: '2026-01-28T09:00:00Z',
    is_own: true,
    lead_count: 180,
    sent_count: 180,
    open_count: 108,
    click_count: 36,
    reply_count: 22,
    bounce_count: 2,
  },
  {
    id: 'demo-camp-4',
    name: 'Series A Founders',
    product: 'Growth Tools',
    brand: 'contndr',
    tone: 'professional',
    status: 'active',
    from_email: 'alex@contndr.com',
    created_at: '2026-03-01T11:00:00Z',
    is_own: true,
    lead_count: 290,
    sent_count: 245,
    open_count: 122,
    click_count: 41,
    reply_count: 18,
    bounce_count: 3,
  },
  {
    id: 'demo-camp-5',
    name: 'E-commerce Re-engagement',
    product: 'Contndr Starter',
    brand: 'contndr',
    tone: 'casual',
    status: 'paused',
    from_email: 'team@contndr.com',
    created_at: '2026-02-10T16:00:00Z',
    is_own: true,
    lead_count: 420,
    sent_count: 210,
    open_count: 84,
    click_count: 21,
    reply_count: 9,
    bounce_count: 5,
  },
];

export const DEMO_RECENT_CAMPAIGNS = DEMO_CAMPAIGNS.slice(0, 5).map(c => ({
  id: c.id,
  name: c.name,
  status: c.status,
  created_at: c.created_at,
  lead_count: c.lead_count,
  sent_count: c.sent_count,
  open_count: c.open_count,
  click_count: c.click_count,
  reply_count: c.reply_count,
}));

export const DEMO_FOLLOW_UPS = [
  { id: 'fu-1', business_name: 'Stripe', contact_name: 'Sarah Chen', email: 'sarah@stripe.com', due_date: '2026-03-07T09:00:00Z', type: 'follow_up' },
  { id: 'fu-2', business_name: 'Notion', contact_name: 'James Park', email: 'james@notion.so', due_date: '2026-03-07T14:00:00Z', type: 'meeting' },
  { id: 'fu-3', business_name: 'Linear', contact_name: 'Karri Saarinen', email: 'karri@linear.app', due_date: '2026-03-08T10:00:00Z', type: 'follow_up' },
];

export const DEMO_LEADS = [
  { id: 'dl-1', business_name: 'Stripe', contact_name: 'Sarah Chen', email: 'sarah@stripe.com', phone: '(415) 555-0198', category: 'Fintech', city: 'San Francisco', state: 'CA', status: 'contacted', last_contacted: '2026-03-04', website: 'stripe.com' },
  { id: 'dl-2', business_name: 'Notion', contact_name: 'James Park', email: 'james@notion.so', phone: '(415) 555-0234', category: 'SaaS', city: 'San Francisco', state: 'CA', status: 'replied', last_contacted: '2026-03-05', website: 'notion.so' },
  { id: 'dl-3', business_name: 'Linear', contact_name: 'Karri Saarinen', email: 'karri@linear.app', phone: '(415) 555-0371', category: 'SaaS', city: 'San Francisco', state: 'CA', status: 'interested', last_contacted: '2026-03-03', website: 'linear.app' },
  { id: 'dl-4', business_name: 'Vercel', contact_name: 'Guillermo Rauch', email: 'guillermo@vercel.com', phone: '(415) 555-0412', category: 'Developer Tools', city: 'San Francisco', state: 'CA', status: 'new', last_contacted: null, website: 'vercel.com' },
  { id: 'dl-5', business_name: 'Figma', contact_name: 'Dylan Field', email: 'dylan@figma.com', phone: '(415) 555-0589', category: 'Design', city: 'San Francisco', state: 'CA', status: 'contacted', last_contacted: '2026-03-02', website: 'figma.com' },
  { id: 'dl-6', business_name: 'Shopify', contact_name: 'Tobi Lutke', email: 'tobi@shopify.com', phone: '(613) 555-0627', category: 'E-commerce', city: 'Ottawa', state: 'ON', status: 'replied', last_contacted: '2026-03-04', website: 'shopify.com' },
  { id: 'dl-7', business_name: 'Datadog', contact_name: 'Olivier Pomel', email: 'olivier@datadoghq.com', phone: '(212) 555-0743', category: 'Monitoring', city: 'New York', state: 'NY', status: 'interested', last_contacted: '2026-03-01', website: 'datadoghq.com' },
  { id: 'dl-8', business_name: 'Airtable', contact_name: 'Howie Liu', email: 'howie@airtable.com', phone: '(415) 555-0856', category: 'SaaS', city: 'San Francisco', state: 'CA', status: 'new', last_contacted: null, website: 'airtable.com' },
  { id: 'dl-9', business_name: 'Retool', contact_name: 'David Hsu', email: 'david@retool.com', phone: '(415) 555-0912', category: 'Developer Tools', city: 'San Francisco', state: 'CA', status: 'contacted', last_contacted: '2026-03-05', website: 'retool.com' },
  { id: 'dl-10', business_name: 'Loom', contact_name: 'Joe Thomas', email: 'joe@loom.com', phone: '(415) 555-0138', category: 'SaaS', city: 'San Francisco', state: 'CA', status: 'new', last_contacted: null, website: 'loom.com' },
  { id: 'dl-11', business_name: 'Amplitude', contact_name: 'Spenser Skates', email: 'spenser@amplitude.com', phone: '(415) 555-0267', category: 'Analytics', city: 'San Francisco', state: 'CA', status: 'contacted', last_contacted: '2026-02-28', website: 'amplitude.com' },
  { id: 'dl-12', business_name: 'PlanetScale', contact_name: 'Sam Lambert', email: 'sam@planetscale.com', phone: '(415) 555-0394', category: 'Database', city: 'San Francisco', state: 'CA', status: 'replied', last_contacted: '2026-03-03', website: 'planetscale.com' },
];

export const DEMO_PIPELINE_DEALS = [
  { 
    id: 'deal-1', 
    contact_name: 'Sarah Chen', 
    business_name: 'Stripe',
    email: 'sarah@stripe.com',
    stage: 'negotiation', 
    value: 85000, 
    currency: 'USD',
    notes: 'Enterprise license discussion',
    category: 'Fintech',
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-03-05T14:30:00Z',
    expected_close_date: '2026-03-15',
    ai_score: 75,
    ai_next_action: 'Schedule final pricing review',
    ai_risk_level: 'low' as const,
  },
  { 
    id: 'deal-2', 
    contact_name: 'James Park', 
    business_name: 'Notion',
    email: 'james@notion.so',
    stage: 'proposal_sent', 
    value: 42000, 
    currency: 'USD',
    notes: 'Team plan proposal sent',
    category: 'SaaS',
    created_at: '2026-02-15T09:00:00Z',
    updated_at: '2026-03-04T11:20:00Z',
    expected_close_date: '2026-03-20',
    ai_score: 60,
    ai_next_action: 'Follow up on proposal feedback',
    ai_risk_level: 'medium' as const,
  },
  { 
    id: 'deal-3', 
    contact_name: 'Karri Saarinen', 
    business_name: 'Linear',
    email: 'karri@linear.app',
    stage: 'engaged', 
    value: 36000, 
    currency: 'USD',
    notes: 'Annual contract discussion',
    category: 'SaaS',
    created_at: '2026-02-20T14:00:00Z',
    updated_at: '2026-03-03T16:45:00Z',
    ai_score: 40,
    ai_next_action: 'Send detailed product demo',
    ai_risk_level: 'medium' as const,
  },
  { 
    id: 'deal-4', 
    contact_name: 'Guillermo Rauch', 
    business_name: 'Vercel',
    email: 'guillermo@vercel.com',
    stage: 'contacted', 
    value: 28000, 
    currency: 'USD',
    notes: 'Pro suite inquiry',
    category: 'Developer Tools',
    created_at: '2026-03-01T10:30:00Z',
    updated_at: '2026-03-02T09:15:00Z',
    ai_score: 25,
    ai_next_action: 'Qualify budget and timeline',
    ai_risk_level: 'medium' as const,
  },
  { 
    id: 'deal-5', 
    contact_name: 'Tobi Lutke', 
    business_name: 'Shopify',
    email: 'tobi@shopify.com',
    stage: 'closed_won', 
    value: 64000, 
    currency: 'USD',
    notes: 'Integration package - closed',
    category: 'E-commerce',
    created_at: '2026-01-20T11:00:00Z',
    updated_at: '2026-02-28T15:00:00Z',
    closed_at: '2026-02-28T15:00:00Z',
    ai_score: 100,
    stripe_payment_status: 'paid',
  },
  { 
    id: 'deal-6', 
    contact_name: 'Olivier Pomel', 
    business_name: 'Datadog',
    email: 'olivier@datadoghq.com',
    stage: 'negotiation', 
    value: 52000, 
    currency: 'USD',
    notes: 'Monitoring bundle pricing discussion',
    category: 'Monitoring',
    created_at: '2026-02-25T13:00:00Z',
    updated_at: '2026-03-05T10:30:00Z',
    expected_close_date: '2026-03-18',
    ai_score: 70,
    ai_next_action: 'Address security concerns',
    ai_risk_level: 'low' as const,
  },
  { 
    id: 'deal-7', 
    contact_name: 'Dylan Field', 
    business_name: 'Figma',
    email: 'dylan@figma.com',
    stage: 'closed_won', 
    value: 31000, 
    currency: 'USD',
    notes: 'Design license - closed',
    category: 'Design',
    created_at: '2026-01-15T14:00:00Z',
    updated_at: '2026-02-20T12:00:00Z',
    closed_at: '2026-02-20T12:00:00Z',
    ai_score: 100,
    qbo_invoice_status: 'paid',
    qbo_invoice_number: 'INV-1024',
  },
  { 
    id: 'deal-8', 
    contact_name: 'David Hsu', 
    business_name: 'Retool',
    email: 'david@retool.com',
    stage: 'proposal_sent', 
    value: 19500, 
    currency: 'USD',
    notes: 'Builder plan proposal',
    category: 'Developer Tools',
    created_at: '2026-03-02T15:30:00Z',
    updated_at: '2026-03-04T14:20:00Z',
    expected_close_date: '2026-03-25',
    ai_score: 55,
    ai_next_action: 'Schedule technical demo',
    ai_risk_level: 'medium' as const,
  },
];

// Demo Lead Finder results (Apollo/People Search)
export const DEMO_APOLLO_RESULTS = [
  {
    id: 'apollo-1',
    person_name: 'Sarah Chen',
    person_title: 'VP of Engineering',
    person_email: 'sarah.chen@stripe.com',
    person_linkedin: 'https://linkedin.com/in/sarahchen',
    company_name: 'Stripe',
    company_domain: 'stripe.com',
    company_industry: 'Fintech',
    company_size: '5001-10000',
    company_location: 'San Francisco, CA',
    confidence: 'verified',
  },
  {
    id: 'apollo-2',
    person_name: 'James Park',
    person_title: 'Head of Product',
    person_email: 'james@notion.so',
    person_linkedin: 'https://linkedin.com/in/jamespark',
    company_name: 'Notion',
    company_domain: 'notion.so',
    company_industry: 'SaaS',
    company_size: '201-500',
    company_location: 'San Francisco, CA',
    confidence: 'verified',
  },
  {
    id: 'apollo-3',
    person_name: 'Emily Rodriguez',
    person_title: 'Director of Sales',
    person_email: 'emily.rodriguez@datadog.com',
    person_linkedin: 'https://linkedin.com/in/emilyrodriguez',
    company_name: 'Datadog',
    company_domain: 'datadoghq.com',
    company_industry: 'Monitoring',
    company_size: '1001-5000',
    company_location: 'New York, NY',
    confidence: 'likely',
  },
  {
    id: 'apollo-4',
    person_name: 'Michael Thompson',
    person_title: 'Chief Marketing Officer',
    person_email: 'michael@shopify.com',
    person_linkedin: 'https://linkedin.com/in/michaelthompson',
    company_name: 'Shopify',
    company_domain: 'shopify.com',
    company_industry: 'E-commerce',
    company_size: '5001-10000',
    company_location: 'Ottawa, ON',
    confidence: 'verified',
  },
  {
    id: 'apollo-5',
    person_name: 'Lisa Wang',
    person_title: 'VP of Growth',
    person_email: 'lisa.wang@figma.com',
    person_linkedin: 'https://linkedin.com/in/lisawang',
    company_name: 'Figma',
    company_domain: 'figma.com',
    company_industry: 'Design',
    company_size: '501-1000',
    company_location: 'San Francisco, CA',
    confidence: 'verified',
  },
  {
    id: 'apollo-6',
    person_name: 'David Kumar',
    person_title: 'Head of Partnerships',
    person_email: 'david@linear.app',
    person_linkedin: 'https://linkedin.com/in/davidkumar',
    company_name: 'Linear',
    company_domain: 'linear.app',
    company_industry: 'SaaS',
    company_size: '51-200',
    company_location: 'San Francisco, CA',
    confidence: 'likely',
  },
];

// Demo Company Search results
export const DEMO_COMPANY_RESULTS = [
  {
    id: 'comp-1',
    name: 'Stripe',
    domain: 'stripe.com',
    industry: 'Fintech',
    employees: '5001-10000',
    location: 'San Francisco, CA',
    description: 'Online payment processing for internet businesses',
    founded: '2010',
    revenue: '$7B+',
    technologies: ['React', 'Ruby', 'Go'],
  },
  {
    id: 'comp-2',
    name: 'Notion',
    domain: 'notion.so',
    industry: 'SaaS',
    employees: '201-500',
    location: 'San Francisco, CA',
    description: 'All-in-one workspace for notes, docs, and collaboration',
    founded: '2016',
    revenue: '$100M+',
    technologies: ['React', 'Node.js', 'PostgreSQL'],
  },
  {
    id: 'comp-3',
    name: 'Linear',
    domain: 'linear.app',
    industry: 'SaaS',
    employees: '51-200',
    location: 'San Francisco, CA',
    description: 'Issue tracking tool for high-performance teams',
    founded: '2019',
    revenue: '$50M+',
    technologies: ['React', 'GraphQL', 'TypeScript'],
  },
  {
    id: 'comp-4',
    name: 'Vercel',
    domain: 'vercel.com',
    industry: 'Developer Tools',
    employees: '201-500',
    location: 'San Francisco, CA',
    description: 'Frontend cloud platform for developers',
    founded: '2015',
    revenue: '$100M+',
    technologies: ['Next.js', 'React', 'Edge Functions'],
  },
];

// Demo Creator Search results
export const DEMO_CREATOR_RESULTS = [
  {
    id: 'creator-1',
    platform: 'youtube',
    channel_name: 'Tech With Tim',
    handle: '@TechWithTim',
    subscriber_count: 1240000,
    video_count: 487,
    avg_views: 125000,
    engagement_rate: 4.2,
    email: 'tim@techwith tim.com',
    topics: ['Python', 'Programming', 'Tutorials'],
    verified: true,
  },
  {
    id: 'creator-2',
    platform: 'youtube',
    channel_name: 'Fireship',
    handle: '@Fireship',
    subscriber_count: 2890000,
    video_count: 342,
    avg_views: 450000,
    engagement_rate: 5.8,
    email: 'jeff@fireship.io',
    topics: ['Web Development', 'JavaScript', 'Tech News'],
    verified: true,
  },
  {
    id: 'creator-3',
    platform: 'instagram',
    channel_name: 'uxdesignmastery',
    handle: '@uxdesignmastery',
    subscriber_count: 385000,
    video_count: 892,
    avg_views: 28000,
    engagement_rate: 3.4,
    email: 'hello@uxdesignmastery.com',
    topics: ['UX Design', 'UI Design', 'Product Design'],
    verified: true,
  },
  {
    id: 'creator-4',
    platform: 'tiktok',
    channel_name: 'CodeWithChris',
    handle: '@codewithchris',
    subscriber_count: 520000,
    video_count: 1240,
    avg_views: 85000,
    engagement_rate: 6.2,
    email: 'chris@codewithchris.com',
    topics: ['Swift', 'iOS Development', 'Coding'],
    verified: true,
  },
];

export const DEMO_INBOX_MESSAGES = [
  { id: 'msg-1', from_name: 'Sarah Chen', from_email: 'sarah@stripe.com', subject: 'Re: Partnership Opportunity', preview: 'Thanks for reaching out! I\'d love to schedule a call to discuss this further...', received_at: '2026-03-06T09:15:00Z', read: false, campaign: 'Q1 Enterprise Outreach' },
  { id: 'msg-2', from_name: 'James Park', from_email: 'james@notion.so', subject: 'Re: Contndr x Notion', preview: 'This sounds interesting. Can you send over some case studies from similar...', received_at: '2026-03-06T08:42:00Z', read: false, campaign: 'SaaS Decision Makers' },
  { id: 'msg-3', from_name: 'Tobi Lutke', from_email: 'tobi@shopify.com', subject: 'Re: E-commerce Growth Tools', preview: 'We\'ve been looking for exactly this kind of solution. Let\'s set up a demo...', received_at: '2026-03-05T16:30:00Z', read: true, campaign: 'E-commerce Re-engagement' },
  { id: 'msg-4', from_name: 'Olivier Pomel', from_email: 'olivier@datadoghq.com', subject: 'Re: Quick question about your platform', preview: 'I forwarded your email to our partnerships team. They should be in touch...', received_at: '2026-03-05T14:20:00Z', read: true, campaign: 'Q1 Enterprise Outreach' },
  { id: 'msg-5', from_name: 'Karri Saarinen', from_email: 'karri@linear.app', subject: 'Re: Building something together', preview: 'Love the vision. We\'re heads down on our v2 launch but let\'s sync after...', received_at: '2026-03-05T11:05:00Z', read: true, campaign: 'SaaS Decision Makers' },
];

// ── Full inbox threads for UnifiedInbox demo mode ──
const _now = Date.now();
export const DEMO_INBOX_THREADS = [
  {
    threadId: 'demo-thread-1',
    leadId: 'dl-1',
    campaignId: 'demo-camp-1',
    brand: 'Contndr',
    leadName: 'Sarah Chen',
    leadEmail: 'sarah@stripe.com',
    leadCompany: 'Stripe',
    lastMessageAt: new Date(_now - 1000 * 60 * 45).toISOString(),
    messageCount: 4,
    unreadCount: 1,
    sentiment: 'positive' as const,
    status: 'active' as const,
    tags: ['Interested', 'Enterprise'],
    messages: [
      { id: 'im-1a', direction: 'sent' as const, from: 'alex@contndr.com', to: 'sarah@stripe.com', subject: 'Partnership Opportunity — Contndr x Stripe', body: 'Hi Sarah,\n\nI came across your work at Stripe and was impressed by the payments infrastructure you\'ve built. We\'re helping high-growth companies automate their outbound pipeline with AI-powered outreach.\n\nWould you be open to a quick call this week?\n\nBest,\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 72).toISOString(), read: true, status: 'opened', openedAt: new Date(_now - 1000 * 60 * 60 * 68).toISOString(), deliveredAt: new Date(_now - 1000 * 60 * 60 * 71).toISOString() },
      { id: 'im-1b', direction: 'received' as const, from: 'sarah@stripe.com', to: 'alex@contndr.com', subject: 'Re: Partnership Opportunity — Contndr x Stripe', body: 'Hi Alex,\n\nThanks for reaching out! We\'ve actually been exploring tools to help our sales team scale their outbound efforts. Your timing is perfect.\n\nCould you send over a brief overview of your enterprise features? I\'d like to loop in our VP of Sales before we schedule a call.\n\nBest,\nSarah', sentAt: new Date(_now - 1000 * 60 * 60 * 48).toISOString(), read: true },
      { id: 'im-1c', direction: 'sent' as const, from: 'alex@contndr.com', to: 'sarah@stripe.com', subject: 'Re: Partnership Opportunity — Contndr x Stripe', body: 'Sarah,\n\nAbsolutely — I\'ve attached our enterprise brief. Key highlights:\n\n• AI-powered email personalization at scale\n• Real-time buying intent signals\n• CRM integration with Salesforce & HubSpot\n• 97.8% deliverability rate\n\nHappy to schedule a demo whenever works for your team. How does next Tuesday or Wednesday look?\n\nBest,\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 24).toISOString(), read: true, status: 'clicked', openedAt: new Date(_now - 1000 * 60 * 60 * 20).toISOString(), clickedAt: new Date(_now - 1000 * 60 * 60 * 19).toISOString(), deliveredAt: new Date(_now - 1000 * 60 * 60 * 23).toISOString() },
      { id: 'im-1d', direction: 'received' as const, from: 'sarah@stripe.com', to: 'alex@contndr.com', subject: 'Re: Partnership Opportunity — Contndr x Stripe', body: 'Alex,\n\nThis looks great — the buying intent feature is exactly what we need. I\'ve looped in Marcus (our VP Sales) and he\'s available Wednesday at 2pm PT. Does that work?\n\nAlso, do you offer custom onboarding for teams of 20+?\n\nThanks,\nSarah', sentAt: new Date(_now - 1000 * 60 * 45).toISOString(), read: false },
    ],
  },
  {
    threadId: 'demo-thread-2',
    leadId: 'dl-2',
    campaignId: 'demo-camp-2',
    brand: 'Contndr',
    leadName: 'James Park',
    leadEmail: 'james@notion.so',
    leadCompany: 'Notion',
    lastMessageAt: new Date(_now - 1000 * 60 * 78).toISOString(),
    messageCount: 3,
    unreadCount: 1,
    sentiment: 'positive' as const,
    status: 'active' as const,
    tags: ['Interested'],
    messages: [
      { id: 'im-2a', direction: 'sent' as const, from: 'alex@contndr.com', to: 'james@notion.so', subject: 'Contndr x Notion — Growing Outbound Together', body: 'Hey James,\n\nBig fan of what Notion is building. I noticed your team is scaling the sales org — we help companies like yours discover and engage decision-makers through intelligent prospecting.\n\nWould love 15 minutes to show you how we\'re different from the usual outreach tools.\n\nCheers,\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 36).toISOString(), read: true, status: 'opened', openedAt: new Date(_now - 1000 * 60 * 60 * 30).toISOString(), deliveredAt: new Date(_now - 1000 * 60 * 60 * 35).toISOString() },
      { id: 'im-2b', direction: 'received' as const, from: 'james@notion.so', to: 'alex@contndr.com', subject: 'Re: Contndr x Notion — Growing Outbound Together', body: 'Alex,\n\nThis sounds interesting. Can you send over some case studies from similar-sized SaaS companies? We\'ve been burned by tools that promise AI personalization but deliver templates.\n\nAlso curious about your data sources — where do leads come from?\n\nJames', sentAt: new Date(_now - 1000 * 60 * 78).toISOString(), read: false },
      { id: 'im-2c', direction: 'sent' as const, from: 'alex@contndr.com', to: 'james@notion.so', subject: 'Re: Contndr x Notion — Growing Outbound Together', body: 'James — great questions.\n\nHere are two case studies from SaaS teams in your range:\n\n1. Linear: 3x reply rate in 30 days\n2. Loom: 47% open rate on cold outreach\n\nOur leads come from a combination of Apollo, verified databases, and our proprietary enrichment engine. Every email is verified before sending.\n\nWant to see it live? I can do a quick screen share tomorrow.\n\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 1).toISOString(), read: true, status: 'delivered', deliveredAt: new Date(_now - 1000 * 60 * 60 * 1).toISOString() },
    ],
  },
  {
    threadId: 'demo-thread-3',
    leadId: 'dl-6',
    campaignId: 'demo-camp-5',
    brand: 'Contndr',
    leadName: 'Tobi Lutke',
    leadEmail: 'tobi@shopify.com',
    leadCompany: 'Shopify',
    lastMessageAt: new Date(_now - 1000 * 60 * 60 * 3.5).toISOString(),
    messageCount: 3,
    unreadCount: 0,
    sentiment: 'positive' as const,
    status: 'active' as const,
    tags: ['Deal', 'Enterprise'],
    messages: [
      { id: 'im-3a', direction: 'sent' as const, from: 'alex@contndr.com', to: 'tobi@shopify.com', subject: 'E-commerce Growth Tools for Shopify', body: 'Hi Tobi,\n\nI know Shopify is focused on empowering merchants — we\'re building tools that help e-commerce companies find and convert their ideal customers through smart outreach.\n\nThought there might be synergy here. Open to a quick chat?\n\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 48).toISOString(), read: true, status: 'opened', openedAt: new Date(_now - 1000 * 60 * 60 * 40).toISOString(), deliveredAt: new Date(_now - 1000 * 60 * 60 * 47).toISOString() },
      { id: 'im-3b', direction: 'received' as const, from: 'tobi@shopify.com', to: 'alex@contndr.com', subject: 'Re: E-commerce Growth Tools for Shopify', body: 'Alex,\n\nWe\'ve been looking for exactly this kind of solution for our merchant success team. They need better tooling to reach high-value prospects.\n\nLet\'s set up a demo for next week. CC my Chief of Staff on the invite — she\'ll coordinate calendars.\n\nTobi', sentAt: new Date(_now - 1000 * 60 * 60 * 3.5).toISOString(), read: true },
      { id: 'im-3c', direction: 'sent' as const, from: 'alex@contndr.com', to: 'tobi@shopify.com', subject: 'Re: E-commerce Growth Tools for Shopify', body: 'Tobi — amazing, really looking forward to it!\n\nI\'ll send over a calendar invite for Tuesday at 11am ET. Will include a brief agenda and our e-commerce playbook.\n\nTalk soon,\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 2).toISOString(), read: true, status: 'delivered', deliveredAt: new Date(_now - 1000 * 60 * 60 * 2).toISOString() },
    ],
  },
  {
    threadId: 'demo-thread-4',
    leadId: 'dl-7',
    campaignId: 'demo-camp-1',
    brand: 'Contndr',
    leadName: 'Olivier Pomel',
    leadEmail: 'olivier@datadoghq.com',
    leadCompany: 'Datadog',
    lastMessageAt: new Date(_now - 1000 * 60 * 60 * 5.3).toISOString(),
    messageCount: 2,
    unreadCount: 0,
    sentiment: 'neutral' as const,
    status: 'active' as const,
    tags: ['Warm'],
    messages: [
      { id: 'im-4a', direction: 'sent' as const, from: 'alex@contndr.com', to: 'olivier@datadoghq.com', subject: 'Quick question about your outbound stack', body: 'Hey Olivier,\n\nI noticed Datadog has been aggressively expanding into the enterprise segment. Curious how your outbound team is currently sourcing and qualifying leads?\n\nWe\'re seeing companies in your space get 3-4x better results with intent-driven prospecting. Happy to share what\'s working.\n\nBest,\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 24).toISOString(), read: true, status: 'opened', openedAt: new Date(_now - 1000 * 60 * 60 * 18).toISOString(), deliveredAt: new Date(_now - 1000 * 60 * 60 * 23).toISOString() },
      { id: 'im-4b', direction: 'received' as const, from: 'olivier@datadoghq.com', to: 'alex@contndr.com', subject: 'Re: Quick question about your outbound stack', body: 'Alex,\n\nAppreciate the note. I forwarded your email to our partnerships team — they handle vendor evaluations for sales tools. They should be in touch within a couple of days.\n\nBest,\nOlivier', sentAt: new Date(_now - 1000 * 60 * 60 * 5.3).toISOString(), read: true },
    ],
  },
  {
    threadId: 'demo-thread-5',
    leadId: 'dl-3',
    campaignId: 'demo-camp-2',
    brand: 'Contndr',
    leadName: 'Karri Saarinen',
    leadEmail: 'karri@linear.app',
    leadCompany: 'Linear',
    lastMessageAt: new Date(_now - 1000 * 60 * 60 * 12).toISOString(),
    messageCount: 2,
    unreadCount: 0,
    sentiment: 'positive' as const,
    status: 'active' as const,
    tags: ['Warm', 'Follow-up'],
    messages: [
      { id: 'im-5a', direction: 'sent' as const, from: 'alex@contndr.com', to: 'karri@linear.app', subject: 'Building something together', body: 'Karri,\n\nHuge respect for what Linear has accomplished — best issue tracker I\'ve used. We\'re building the outreach layer for fast-moving teams like yours.\n\nWould love to explore if there\'s a fit. Even if not, happy to trade notes on building dev tools.\n\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 36).toISOString(), read: true, status: 'opened', openedAt: new Date(_now - 1000 * 60 * 60 * 28).toISOString(), deliveredAt: new Date(_now - 1000 * 60 * 60 * 35).toISOString() },
      { id: 'im-5b', direction: 'received' as const, from: 'karri@linear.app', to: 'alex@contndr.com', subject: 'Re: Building something together', body: 'Alex,\n\nLove the vision. We\'re heads down on our v2 launch right now but let\'s sync after March 15th. I\'m genuinely curious about the intent signals feature — that could be game-changing for our GTM team.\n\nRemind me in a couple weeks?\n\nKarri', sentAt: new Date(_now - 1000 * 60 * 60 * 12).toISOString(), read: true },
    ],
  },
  {
    threadId: 'demo-thread-6',
    leadId: 'dl-5',
    campaignId: 'demo-camp-4',
    brand: 'Contndr',
    leadName: 'Dylan Field',
    leadEmail: 'dylan@figma.com',
    leadCompany: 'Figma',
    lastMessageAt: new Date(_now - 1000 * 60 * 60 * 26).toISOString(),
    messageCount: 3,
    unreadCount: 0,
    sentiment: 'positive' as const,
    status: 'active' as const,
    tags: ['Interested'],
    messages: [
      { id: 'im-6a', direction: 'sent' as const, from: 'alex@contndr.com', to: 'dylan@figma.com', subject: 'Scaling outbound at Figma', body: 'Hey Dylan,\n\nFigma\'s growth has been incredible. As you scale the enterprise sales motion, outbound prospecting becomes critical. We\'re helping product-led companies layer on targeted outreach without losing their brand voice.\n\nWorth a look?\n\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 72).toISOString(), read: true, status: 'clicked', openedAt: new Date(_now - 1000 * 60 * 60 * 64).toISOString(), clickedAt: new Date(_now - 1000 * 60 * 60 * 63).toISOString(), deliveredAt: new Date(_now - 1000 * 60 * 60 * 71).toISOString() },
      { id: 'im-6b', direction: 'received' as const, from: 'dylan@figma.com', to: 'alex@contndr.com', subject: 'Re: Scaling outbound at Figma', body: 'Alex — great timing. We just kicked off a project to improve our outbound motion. The AI personalization angle is what caught my eye.\n\nCan you do a walkthrough for me and our Head of Revenue? Sometime next week works.\n\nDylan', sentAt: new Date(_now - 1000 * 60 * 60 * 48).toISOString(), read: true },
      { id: 'im-6c', direction: 'sent' as const, from: 'alex@contndr.com', to: 'dylan@figma.com', subject: 'Re: Scaling outbound at Figma', body: 'Dylan — that\'s perfect.\n\nI\'ll set up a 30-min walkthrough for next Thursday. Will tailor it to the PLG → enterprise transition since that\'s exactly our sweet spot.\n\nCalendar invite coming shortly!\n\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 26).toISOString(), read: true, status: 'delivered', deliveredAt: new Date(_now - 1000 * 60 * 60 * 26).toISOString() },
    ],
  },
  {
    threadId: 'demo-thread-7',
    leadId: 'dl-4',
    campaignId: 'demo-camp-4',
    brand: 'Contndr',
    leadName: 'Guillermo Rauch',
    leadEmail: 'guillermo@vercel.com',
    leadCompany: 'Vercel',
    lastMessageAt: new Date(_now - 1000 * 60 * 60 * 48).toISOString(),
    messageCount: 2,
    unreadCount: 0,
    sentiment: 'neutral' as const,
    status: 'active' as const,
    tags: [],
    messages: [
      { id: 'im-7a', direction: 'sent' as const, from: 'alex@contndr.com', to: 'guillermo@vercel.com', subject: 'Developer-first outreach for Vercel', body: 'Guillermo,\n\nVercel has nailed developer experience. We\'re trying to do the same for outbound sales — making it feel native, not spammy.\n\nWould love to show you what we\'re building. Especially think the signal-driven approach would resonate with how Vercel thinks about product.\n\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 96).toISOString(), read: true, status: 'delivered', deliveredAt: new Date(_now - 1000 * 60 * 60 * 95).toISOString() },
      { id: 'im-7b', direction: 'sent' as const, from: 'alex@contndr.com', to: 'guillermo@vercel.com', subject: 'Re: Developer-first outreach for Vercel', body: 'Hey Guillermo — just bumping this up. Totally understand if the timing isn\'t right. Happy to reconnect whenever it makes sense.\n\nIn the meantime, we published a report on how dev tool companies are rethinking outbound — link below if you\'re curious.\n\nBest,\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 48).toISOString(), read: true, status: 'opened', openedAt: new Date(_now - 1000 * 60 * 60 * 36).toISOString(), deliveredAt: new Date(_now - 1000 * 60 * 60 * 47).toISOString() },
    ],
  },
  {
    threadId: 'demo-thread-8',
    leadId: 'dl-9',
    campaignId: 'demo-camp-2',
    brand: 'Contndr',
    leadName: 'David Hsu',
    leadEmail: 'david@retool.com',
    leadCompany: 'Retool',
    lastMessageAt: new Date(_now - 1000 * 60 * 60 * 8).toISOString(),
    messageCount: 4,
    unreadCount: 1,
    sentiment: 'positive' as const,
    status: 'active' as const,
    tags: ['Interested', 'Technical'],
    messages: [
      { id: 'im-8a', direction: 'sent' as const, from: 'alex@contndr.com', to: 'david@retool.com', subject: 'Outbound tooling for Retool', body: 'David,\n\nRetool is one of those tools every dev team loves. We\'re building something similar for sales teams — an internal-tool-like approach to outbound prospecting.\n\nWould love 15 minutes to show the tech behind it. Think you\'d appreciate the architecture.\n\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 60).toISOString(), read: true, status: 'opened', openedAt: new Date(_now - 1000 * 60 * 60 * 52).toISOString(), deliveredAt: new Date(_now - 1000 * 60 * 60 * 59).toISOString() },
      { id: 'im-8b', direction: 'received' as const, from: 'david@retool.com', to: 'alex@contndr.com', subject: 'Re: Outbound tooling for Retool', body: 'Alex — love the angle. We\'re actually evaluating outbound platforms right now.\n\nQuick questions: Do you have an API? And can we integrate with our existing Salesforce instance?\n\nDavid', sentAt: new Date(_now - 1000 * 60 * 60 * 36).toISOString(), read: true },
      { id: 'im-8c', direction: 'sent' as const, from: 'alex@contndr.com', to: 'david@retool.com', subject: 'Re: Outbound tooling for Retool', body: 'David — great timing!\n\nYes to both:\n• Full REST API with webhooks\n• Native Salesforce bidirectional sync\n• Also HubSpot, Slack, and QuickBooks integrations\n\nI can do a technical deep-dive if that\'s helpful. How\'s Thursday?\n\nAlex', sentAt: new Date(_now - 1000 * 60 * 60 * 24).toISOString(), read: true, status: 'clicked', openedAt: new Date(_now - 1000 * 60 * 60 * 18).toISOString(), clickedAt: new Date(_now - 1000 * 60 * 60 * 17).toISOString(), deliveredAt: new Date(_now - 1000 * 60 * 60 * 23).toISOString() },
      { id: 'im-8d', direction: 'received' as const, from: 'david@retool.com', to: 'alex@contndr.com', subject: 'Re: Outbound tooling for Retool', body: 'Thursday works. Can you make it 3pm PT? I\'ll pull in our VP Eng too — he\'ll want to see the API.\n\nAlso, we\'d need SSO support. Do you have that?\n\nDavid', sentAt: new Date(_now - 1000 * 60 * 60 * 8).toISOString(), read: false },
    ],
  },
];

export const DEMO_INBOX_STATS = {
  totalConversations: 8,
  unreadCount: 3,
  positiveCount: 5,
  neutralCount: 2,
  negativeCount: 0,
  interestedCount: 4,
};

// ── Team page demo data ──
export const DEMO_TEAM_MEMBERS = [
  {
    id: 'demo-tm-1', name: 'Or Briga', email: 'or@contndr.com', avatar_url: null, is_you: true,
    leads: 847, leads_this_month: 134, emails_sent: 3842, emails_opened: 1729, emails_clicked: 461,
    open_rate: 45.0, click_rate: 12.0, replies: 312, meetings: 48, pipeline: 156, campaigns: 14, revenue: 84200, conversions: 156,
  },
  {
    id: 'demo-tm-2', name: 'Sarah Chen', email: 'sarah@contndr.com', avatar_url: null, is_you: false,
    leads: 623, leads_this_month: 97, emails_sent: 2915, emails_opened: 1370, emails_clicked: 321,
    open_rate: 47.0, click_rate: 11.0, replies: 248, meetings: 37, pipeline: 118, campaigns: 11, revenue: 62400, conversions: 118,
  },
  {
    id: 'demo-tm-3', name: 'Jake Morrison', email: 'jake@contndr.com', avatar_url: null, is_you: false,
    leads: 531, leads_this_month: 82, emails_sent: 2480, emails_opened: 1042, emails_clicked: 248,
    open_rate: 42.0, click_rate: 10.0, replies: 196, meetings: 29, pipeline: 94, campaigns: 9, revenue: 41800, conversions: 94,
  },
  {
    id: 'demo-tm-4', name: 'Maya Patel', email: 'maya@contndr.com', avatar_url: null, is_you: false,
    leads: 412, leads_this_month: 68, emails_sent: 1956, emails_opened: 860, emails_clicked: 195,
    open_rate: 44.0, click_rate: 10.0, replies: 158, meetings: 22, pipeline: 73, campaigns: 7, revenue: 29500, conversions: 73,
  },
  {
    id: 'demo-tm-5', name: 'Liam Foster', email: 'liam@contndr.com', avatar_url: null, is_you: false,
    leads: 289, leads_this_month: 41, emails_sent: 1340, emails_opened: 536, emails_clicked: 121,
    open_rate: 40.0, click_rate: 9.0, replies: 104, meetings: 14, pipeline: 48, campaigns: 5, revenue: 17600, conversions: 48,
  },
];

// Team settings demo data
export const DEMO_TEAM_SETTINGS = {
  teamId: 'demo-team-001',
  isOwner: true,
  members: [
    { id: 'demo-tm-1', email: 'or@contndr.com', role: 'owner', status: 'active' as const, joined_at: '2025-09-01T00:00:00Z', name: 'Or Briga' },
    { id: 'demo-tm-2', email: 'sarah@contndr.com', role: 'admin', status: 'active' as const, joined_at: '2025-10-15T00:00:00Z', name: 'Sarah Chen' },
    { id: 'demo-tm-3', email: 'jake@contndr.com', role: 'member', status: 'active' as const, joined_at: '2025-11-20T00:00:00Z', name: 'Jake Morrison' },
    { id: 'demo-tm-4', email: 'maya@contndr.com', role: 'member', status: 'active' as const, joined_at: '2026-01-05T00:00:00Z', name: 'Maya Patel' },
    { id: 'demo-tm-5', email: 'liam@contndr.com', role: 'member', status: 'active' as const, joined_at: '2026-02-01T00:00:00Z', name: 'Liam Foster' },
  ],
  invites: [
    { email: 'alex@contndr.com', role: 'member', token: 'demo-token-1', created_at: '2026-03-05T10:00:00Z' },
  ],
  plan: 'growth',
  limit: 10,
  usage: 5,
};

// ─── Social Post Syncer Demo Data ────────────────────────────────────

export const DEMO_SOCIAL_ACCOUNTS = [
  {
    id: 'linkedin_demo-user-1',
    platform: 'linkedin' as const,
    platformUserId: 'demo-user-1',
    displayName: 'Or Briga',
    email: 'or@contndr.com',
    avatarUrl: '',
    scopes: ['openid', 'profile', 'email', 'w_member_social'],
    connectedAt: '2026-02-15T10:00:00Z',
    expiresAt: Date.now() + 60 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'facebook_demo-page-1',
    platform: 'facebook' as const,
    platformUserId: 'demo-page-1',
    displayName: 'Contndr',
    avatarUrl: '',
    scopes: ['pages_manage_posts', 'pages_read_engagement', 'pages_show_list', 'business_management'],
    connectedAt: '2026-02-20T14:00:00Z',
    expiresAt: Date.now() + 60 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'instagram_demo-ig-1',
    platform: 'instagram' as const,
    platformUserId: 'demo-ig-1',
    displayName: '@contndr',
    avatarUrl: '',
    scopes: ['instagram_basic', 'instagram_content_publish'],
    connectedAt: '2026-02-20T14:00:00Z',
    expiresAt: Date.now() + 60 * 24 * 60 * 60 * 1000,
  },
];

export const DEMO_SOCIAL_POSTS = [
  {
    id: 'demo-post-1',
    content: "Excited to announce Contndr's new AI-powered lead scoring! 🚀 We've been working hard to help sales teams prioritize the right prospects.\n\n#SalesTech #AI #ColdOutreach",
    platforms: ['linkedin', 'facebook'],
    status: 'published',
    scheduledAt: undefined,
    publishedAt: '2026-03-04T14:30:00Z',
    createdAt: '2026-03-04T14:00:00Z',
    updatedAt: '2026-03-04T14:30:00Z',
    results: {
      linkedin: {
        status: 'published',
        postUrl: 'https://www.linkedin.com/feed/update/urn:li:activity:1234567890',
        platformPostId: 'urn:li:ugcPost:1234567890',
        publishedAt: '2026-03-04T14:30:00Z',
        engagement: { impressions: 4820, clicks: 186, likes: 147, comments: 23, shares: 31, lastSyncedAt: '2026-03-06T20:00:00Z' },
      },
      facebook: {
        status: 'published',
        postUrl: 'https://www.facebook.com/contndr/posts/1234567890',
        platformPostId: 'fb_1234567890',
        publishedAt: '2026-03-04T14:30:00Z',
        engagement: { impressions: 2310, reach: 1870, likes: 89, comments: 12, shares: 18, reactions: 95, lastSyncedAt: '2026-03-06T20:00:00Z' },
      },
    },
  },
  {
    id: 'demo-post-2',
    content: "3 cold email mistakes that are killing your reply rates:\n\n1. Generic openers (\"Hope you're well\")\n2. No personalization beyond {first_name}\n3. Asking for a 30-min call in the first email\n\nWhat would you add? 👇",
    platforms: ['linkedin'],
    status: 'published',
    scheduledAt: undefined,
    publishedAt: '2026-03-02T09:15:00Z',
    createdAt: '2026-03-02T08:00:00Z',
    updatedAt: '2026-03-02T09:15:00Z',
    results: {
      linkedin: {
        status: 'published',
        postUrl: 'https://www.linkedin.com/feed/update/urn:li:activity:1234567891',
        platformPostId: 'urn:li:ugcPost:1234567891',
        publishedAt: '2026-03-02T09:15:00Z',
        engagement: { impressions: 12400, clicks: 520, likes: 384, comments: 67, shares: 92, lastSyncedAt: '2026-03-06T18:00:00Z' },
      },
    },
  },
  {
    id: 'demo-post-3',
    content: "Just crossed 10,000 outreach emails sent through Contndr with a 45% open rate 📈\n\nThe secret? Our multi-channel warm-up engine ensures your emails actually land in the inbox.\n\nDM me if you want early access to our growth plan.",
    platforms: ['linkedin', 'facebook', 'instagram'],
    status: 'scheduled',
    scheduledAt: '2026-03-07T10:00:00Z',
    publishedAt: undefined,
    createdAt: '2026-03-05T16:00:00Z',
    updatedAt: '2026-03-05T16:00:00Z',
    results: {
      linkedin: { status: 'scheduled' },
      facebook: { status: 'scheduled' },
      instagram: { status: 'scheduled' },
    },
  },
  {
    id: 'demo-post-4',
    content: "Building in public: This week we shipped the Social Post Syncer inside Contndr.\n\nNow you can compose, schedule, and publish to LinkedIn, Facebook, and Instagram directly from your outreach dashboard. One post, multiple platforms.\n\n#BuildInPublic #SaaS",
    platforms: ['linkedin', 'facebook'],
    status: 'draft',
    scheduledAt: undefined,
    publishedAt: undefined,
    createdAt: '2026-03-06T08:00:00Z',
    updatedAt: '2026-03-06T08:00:00Z',
    results: {
      linkedin: { status: 'draft' },
      facebook: { status: 'draft' },
    },
  },
  {
    id: 'demo-post-5',
    content: "Behind every great sales team is a process that actually works.\n\nHere's how Contndr helps you go from cold lead to closed deal:\n→ AI enrichment & scoring\n→ Multi-channel sequences\n→ Social post scheduling\n→ Real-time intent signals\n\nReady to level up your outreach game?",
    platforms: ['facebook'],
    status: 'published',
    scheduledAt: undefined,
    publishedAt: '2026-03-05T11:00:00Z',
    createdAt: '2026-03-05T10:30:00Z',
    updatedAt: '2026-03-05T11:00:00Z',
    results: {
      facebook: {
        status: 'published',
        postUrl: 'https://www.facebook.com/contndr/posts/9876543210',
        platformPostId: 'fb_9876543210',
        publishedAt: '2026-03-05T11:00:00Z',
        engagement: { impressions: 1580, reach: 1240, likes: 62, comments: 8, shares: 11, reactions: 68, lastSyncedAt: '2026-03-06T19:30:00Z' },
      },
    },
  },
];